# Generated by Django 4.1.4 on 2023-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profile_status',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('SUSPENDED', 'SUSPENDED')], default='REGISTRATION', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_status',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('SUSPENDED', 'SUSPENDED')], default='REGISTRATION', max_length=255),
        ),
    ]
