# Generated by Django 4.1.4 on 2023-01-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_publicuser_profile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
    ]
