# Generated by Django 4.1.4 on 2023-01-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_status',
            field=models.CharField(choices=[('REGISTRATION', 'REGISTRATION'), ('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('SUSPENDED', 'SUSPENDED')], default='REGISTRATION', max_length=255),
        ),
    ]
