# Generated by Django 4.1.4 on 2023-01-11 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_alter_appmodel_created_at_alter_appmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystorage',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_keys', to='video.appmodel'),
        ),
        migrations.AddField(
            model_name='keystorage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
