# Generated by Django 4.1.4 on 2022-12-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_keystorage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystorage',
            name='key',
            field=models.TextField(unique=True),
        ),
    ]
