# Generated by Django 4.1.4 on 2023-01-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_product_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystorage',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
