# Generated by Django 4.1.4 on 2022-12-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_keystorage_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keystorage',
            old_name='expiry_date',
            new_name='expires_at',
        ),
    ]
