# Generated by Django 4.1.4 on 2023-01-12 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0006_keystorage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystorage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
