# Generated by Django 4.1.4 on 2022-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_rename_expiry_date_keystorage_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystorage',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
