# Generated by Django 4.1.4 on 2023-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_keystorage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystorage',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
