# Generated by Django 4.1.4 on 2023-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_keystorage_date_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
