# Generated by Django 4.1.4 on 2022-12-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_keystorage_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystorage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
