# Generated by Django 4.1.4 on 2023-03-02 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_appmodel_encryptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_type', models.CharField(default='player', max_length=1000)),
                ('version', models.CharField(default='1.0.0', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
