# Generated by Django 4.1.4 on 2022-12-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_product_keystorage_product_video_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='encryptor',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
