# Generated by Django 4.1.4 on 2022-12-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_alter_product_encryptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystorage',
            name='time_stamp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystorage',
            name='validity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='keystorage',
            name='watermark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
