# Generated by Django 4.1.4 on 2023-01-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_product_long_description_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
