# Generated by Django 4.1.4 on 2023-01-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystorage',
            name='videos',
            field=models.ManyToManyField(related_name='video_keys', to='video.video'),
        ),
    ]
